name: SocialRub
favicon: null
layout_spectrum: 1
typography_spectrum: 0.22804
title: SocialRub
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#139914'
    - '#797979'
    - '#d9d9d9'
    - '#b4b4b4'
  brandStrength: 1
  lightness: 0.6989975238684565
  saturation: 0.9026888245716691
  rhythmicContrast: 0.8563550990074873
purpose: []
