name: SocialRub
favicon: null
layout_spectrum: 0.09764641127549112
typography_spectrum: 0.44436869234777987
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9354653649497777
  lightness: 0.6989975238684565
  saturation: 0.9026888245716691
  rhythmicContrast: 0.8563550990074873
purpose: []
